// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxybbN4Qx2XFZluxk4eL-ctjJy_wYo1dc',
    appId: '1:411753239735:web:1c4c57e5621249a21e2932',
    messagingSenderId: '411753239735',
    projectId: 'shop-app-4b8ef',
    authDomain: 'shop-app-4b8ef.firebaseapp.com',
    storageBucket: 'shop-app-4b8ef.firebasestorage.app',
    measurementId: 'G-X20P8PBKJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAcJQYe9zN5ufmY-duGk0t82BZ8G2DM0',
    appId: '1:411753239735:android:a9e695a6f514ec721e2932',
    messagingSenderId: '411753239735',
    projectId: 'shop-app-4b8ef',
    storageBucket: 'shop-app-4b8ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbc2VCUtVtX5VwnkeJ7zfVe16MoeDVygo',
    appId: '1:411753239735:ios:9b6af9bd258d53601e2932',
    messagingSenderId: '411753239735',
    projectId: 'shop-app-4b8ef',
    storageBucket: 'shop-app-4b8ef.firebasestorage.app',
    iosBundleId: 'uz.shah.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbc2VCUtVtX5VwnkeJ7zfVe16MoeDVygo',
    appId: '1:411753239735:ios:9b6af9bd258d53601e2932',
    messagingSenderId: '411753239735',
    projectId: 'shop-app-4b8ef',
    storageBucket: 'shop-app-4b8ef.firebasestorage.app',
    iosBundleId: 'uz.shah.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxybbN4Qx2XFZluxk4eL-ctjJy_wYo1dc',
    appId: '1:411753239735:web:2587b60d94fc1eb61e2932',
    messagingSenderId: '411753239735',
    projectId: 'shop-app-4b8ef',
    authDomain: 'shop-app-4b8ef.firebaseapp.com',
    storageBucket: 'shop-app-4b8ef.firebasestorage.app',
    measurementId: 'G-MXMRTSQMHS',
  );
}
